### ISSUE TITLE
not working blank page with zero flashing under cursor

### ISSUE THREAD

**Issue by Inc0n** [johnchen902/sliding-game-ai#1]
used gcc version 8.2.1

```
$ ncursesw6-config  --abi-version
6
$ ncursesw6-config  --mouse-version
2

```

What could have potentially gone wrong ??

**Comment by johnchen902** [comment]
I have the same versions (Arch Linux). Cannot reproduce. What terminal emulator do you use?

**Comment by Inc0n** [comment]
yeah sorry about this, i knew it was the color theme i use in my xresource messes up the interface
